### ISSUE TITLE
Pulish sonatype release

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/afterburner.fx#6]
https://central.sonatype.org/publish/publish-gradle/#metadata-definition-and-upload

**Comment by Siedlerchr** [comment]
https://github.com/gradle-nexus/publish-plugin/

**Comment by tobiasdiez** [comment]
https://github.com/tobiasdiez/EasyBind/blob/main/.github/workflows/publish.yml

**Comment by Siedlerchr** [comment]
Thx! Will take a look at it!
